### ISSUE TITLE
How can I build the firmware?

### ISSUE THREAD

**Issue by Giszmo** [Sallet-Atelas/SalletOne#1]
This repository only containing two commits, with no actual product videos or photos or unboxing videos of actual users I'm not sure this is an actual product but if it's open source, I'd be curious to know how to update the product, how the device verifies to only update to signed binaries, where to find the binaries and ... how to build it myself. Where can I find all this information?

**Comment by SalletOne** [comment]
this project is only core encryption algorithm about bitcoin and ethereum etc, if you want to use open source to build by yourself，you can download sallet-one-cold project and build it.
if you want to know more information, you can visit our official website: https://www.salletone.com.

**Comment by Giszmo** [comment]
Thanks. Will open an issue there ...
